const egyptGovernorates = [
    "alexandria",
    "aswan",
    "asyut",
    "beheira",
    "beni suef",
    "cairo",
    "dakahlia",
    "damietta",
    "faiyum",
    "gharbeya",
    "giza",
    "ismailia",
    "kafr el-sheikh",
    "luxor",
    "matrouh",
    "minya",
    "monufia",
    "new valley",
    "north sinai",
    "port said",
    "qalyubia",
    "qena",
    "red sea",
    "sohag",
    "south sinai",
    "suez",
  ];

  export {egyptGovernorates}